# Generated by Django 4.1.4 on 2023-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.CharField(max_length=10000)),
                ('heading', models.CharField(max_length=1000)),
                ('paragraph_one', models.TextField()),
                ('paragraph_two', models.TextField()),
                ('paragraph_three', models.TextField()),
                ('paragraph_four', models.TextField()),
                ('post_published', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('creater', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-post_published'],
            },
        ),
    ]
