# Generated by Django 4.1.4 on 2023-08-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=10000)),
                ('content', models.TextField()),
                ('post_published', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('creater', models.CharField(max_length=255)),
            ],
        ),
    ]
