# Generated by Django 4.2.6 on 2024-03-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_post_heading_remove_post_paragraph_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_published',
            field=models.BooleanField(default=False),
        ),
    ]
